name: gate_generator
description: Injection generator for your flutter/dart applications
version: 0.0.3
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  analyzer: ^2.3.0
  build: ^2.1.0
  code_builder: ^4.1.0
  dart_style: ^2.2.0
  gate: ^0.0.2
  # gate: 
  #   path: ../gate
  glob: ^2.0.2
  meta: ^1.7.0
  path: ^1.8.0
  quiver: ^3.0.1
  source_gen: ^1.1.0
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  lints: ^1.0.0
  mocktail: ^0.1.4
  source_gen_test: ^1.0.1
  test: ^1.16.0
