name: gate_generator
description: Dependency Injection generator for your flutter/dart applications.
  This uses annotations and build_runner.
version: 1.0.0
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  gate: ^1.0.0
  glob: ^2.1.1
  meta: ^1.8.0
  path: ^1.8.2
  quiver: ^3.1.0
  source_gen: ^1.2.6
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: ^1.22.0
