name: gate_generator
description: Dependency Injection generator for your flutter/dart applications.
  This uses annotations and build_runner.
version: 0.0.3+6
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  build: ^2.1.0
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  gate: ^0.0.2
  # gate: 
  #   path: ../gate 
  glob: ^2.0.2
  meta: ^1.7.0
  path: ^1.8.0
  quiver: ^3.0.1+1
  source_gen: ^1.2.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lints: ^1.0.1
  mocktail: ^0.3.0
  source_gen_test: ^1.0.2
  test: ^1.16.0
