name: gate
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:


dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.17.12
