name: gate
description: Annotations for gate_generator
version: 1.1.0
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.14.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.0
