name: gate
description: Annotations for gate_generator
version: 0.0.2
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.17.12
