name: gate
description: Annotations for gate_generator
version: 1.0.1
repository: https://github.com/Apparence-io/gate

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.0
